In [1]:
import pandas as pd 

df = pd.read_table(r'C:\Users\Francesca\Desktop\D5 - CPI from Eurostat (clean and drop).tsv', sep='\t', header=0)
df

   freq,unit,geo\TIME_PERIOD  2015   2016   2017   2018   2019   2020   2021
0                    A,NR,AL     36     39     38     36     35     36     35
1                    A,NR,AT     76     75     75     76     77     76     74
2                    A,NR,BE     77     77     75     75     75     76     73
3                    A,NR,BG     41     41     43     42     43     44     42
4                    A,NR,CH     86     86     85     85     85     85     84
5                    A,NR,CY     61     55     57     59     58     57     53
6                    A,NR,CZ     56     55     57     59     56     54     54
7                    A,NR,DE     81     81     81     80     80     80     80
8                    A,NR,DK     91     90     88     88     87     88     88
9                    A,NR,EE     70     70     71     73     74     75     74
10                   A,NR,EL     46     44     48     45     48     50     49
11                   A,NR,ES     58     58     57     58     62     62     61
12                   A,NR,FI     90     89     85     85     86     85     88
13                   A,NR,FR     70     69     70     72     69     69     71
14                   A,NR,HR     51     49     49     48     47     47     47
15                   A,NR,HU     51     48     45     46     44     44     43
16                   A,NR,IE     75     73     74     73     74     72     74
17                   A,NR,IS     79     78     77     76     78     75     74
18                   A,NR,IT     44     47     50     52     53     53     56
19                   A,NR,JP     75     72     73     73     73     74     73
20                   A,NR,KR     54     53     54     57     59     61     62
21                   A,NR,LT     59     59     59     59     60     60     61
22                   A,NR,LU     85     81     82     81     80     80     81
23                   A,NR,LV     56     57     58     58     56     57     59
24                   A,NR,ME     44     45     46     45     45     45     46
25                   A,NR,MK     42     37     35     37     35     35     39
26                   A,NR,MT     60     55     56     54     54     53     54
27                   A,NR,NL     84     83     82     82     82     82     82
28                   A,NR,NO     88     85     85     84     84     84     85
29                   A,NR,PL     63     62     60     60     58     56     56
30                   A,NR,PT     64     62     63     64     62     61     62
31                   A,NR,RO     46     48     48     47     44     44     45
32                   A,NR,RS     40     42     41     39     39     38     38
33                   A,NR,RU     29     29     29     28     28     30     29
34                   A,NR,SE     89     88     84     85     85     85     85
35                   A,NR,SI     60     61     61     60     60     60     57
36                   A,NR,SK     51     51     50     50     50     49     52
37                   A,NR,TR     42     41     40     41     39     40     38
38                   A,NR,UK     81     81     82     80     77     77     78
39                   A,NR,US     76     74     75     71     69     67     67

In [2]:
to_sep = pd.DataFrame(df.iloc[:,0])
to_sep

   freq,unit,geo\TIME_PERIOD
0                    A,NR,AL
1                    A,NR,AT
2                    A,NR,BE
3                    A,NR,BG
4                    A,NR,CH
5                    A,NR,CY
6                    A,NR,CZ
7                    A,NR,DE
8                    A,NR,DK
9                    A,NR,EE
10                   A,NR,EL
11                   A,NR,ES
12                   A,NR,FI
13                   A,NR,FR
14                   A,NR,HR
15                   A,NR,HU
16                   A,NR,IE
17                   A,NR,IS
18                   A,NR,IT
19                   A,NR,JP
20                   A,NR,KR
21                   A,NR,LT
22                   A,NR,LU
23                   A,NR,LV
24                   A,NR,ME
25                   A,NR,MK
26                   A,NR,MT
27                   A,NR,NL
28                   A,NR,NO
29                   A,NR,PL
30                   A,NR,PT
31                   A,NR,RO
32                   A,NR,RS
33                   A,NR,RU
34                   A,NR,SE
35                   A,NR,SI
36                   A,NR,SK
37                   A,NR,TR
38                   A,NR,UK
39                   A,NR,US

In [3]:
to_sep[['freq', 'unit','geo']] = to_sep["freq,unit,geo\TIME_PERIOD"].str.split(",", expand = True)
to_sep

   freq,unit,geo\TIME_PERIOD freq unit geo
0                    A,NR,AL    A   NR  AL
1                    A,NR,AT    A   NR  AT
2                    A,NR,BE    A   NR  BE
3                    A,NR,BG    A   NR  BG
4                    A,NR,CH    A   NR  CH
5                    A,NR,CY    A   NR  CY
6                    A,NR,CZ    A   NR  CZ
7                    A,NR,DE    A   NR  DE
8                    A,NR,DK    A   NR  DK
9                    A,NR,EE    A   NR  EE
10                   A,NR,EL    A   NR  EL
11                   A,NR,ES    A   NR  ES
12                   A,NR,FI    A   NR  FI
13                   A,NR,FR    A   NR  FR
14                   A,NR,HR    A   NR  HR
15                   A,NR,HU    A   NR  HU
16                   A,NR,IE    A   NR  IE
17                   A,NR,IS    A   NR  IS
18                   A,NR,IT    A   NR  IT
19                   A,NR,JP    A   NR  JP
20                   A,NR,KR    A   NR  KR
21                   A,NR,LT    A   NR  LT
22                   A,NR,LU    A   NR  LU
23                   A,NR,LV    A   NR  LV
24                   A,NR,ME    A   NR  ME
25                   A,NR,MK    A   NR  MK
26                   A,NR,MT    A   NR  MT
27                   A,NR,NL    A   NR  NL
28                   A,NR,NO    A   NR  NO
29                   A,NR,PL    A   NR  PL
30                   A,NR,PT    A   NR  PT
31                   A,NR,RO    A   NR  RO
32                   A,NR,RS    A   NR  RS
33                   A,NR,RU    A   NR  RU
34                   A,NR,SE    A   NR  SE
35                   A,NR,SI    A   NR  SI
36                   A,NR,SK    A   NR  SK
37                   A,NR,TR    A   NR  TR
38                   A,NR,UK    A   NR  UK
39                   A,NR,US    A   NR  US

In [4]:
df = to_sep.merge(df, left_index=True, right_index=True)
df = df.drop(columns=["freq,unit,geo\TIME_PERIOD_x", "freq,unit,geo\TIME_PERIOD_y"])
df

   freq unit geo  2015   2016   2017   2018   2019   2020   2021
0     A   NR  AL     36     39     38     36     35     36     35
1     A   NR  AT     76     75     75     76     77     76     74
2     A   NR  BE     77     77     75     75     75     76     73
3     A   NR  BG     41     41     43     42     43     44     42
4     A   NR  CH     86     86     85     85     85     85     84
5     A   NR  CY     61     55     57     59     58     57     53
6     A   NR  CZ     56     55     57     59     56     54     54
7     A   NR  DE     81     81     81     80     80     80     80
8     A   NR  DK     91     90     88     88     87     88     88
9     A   NR  EE     70     70     71     73     74     75     74
10    A   NR  EL     46     44     48     45     48     50     49
11    A   NR  ES     58     58     57     58     62     62     61
12    A   NR  FI     90     89     85     85     86     85     88
13    A   NR  FR     70     69     70     72     69     69     71
14    A   NR  HR     51     49     49     48     47     47     47
15    A   NR  HU     51     48     45     46     44     44     43
16    A   NR  IE     75     73     74     73     74     72     74
17    A   NR  IS     79     78     77     76     78     75     74
18    A   NR  IT     44     47     50     52     53     53     56
19    A   NR  JP     75     72     73     73     73     74     73
20    A   NR  KR     54     53     54     57     59     61     62
21    A   NR  LT     59     59     59     59     60     60     61
22    A   NR  LU     85     81     82     81     80     80     81
23    A   NR  LV     56     57     58     58     56     57     59
24    A   NR  ME     44     45     46     45     45     45     46
25    A   NR  MK     42     37     35     37     35     35     39
26    A   NR  MT     60     55     56     54     54     53     54
27    A   NR  NL     84     83     82     82     82     82     82
28    A   NR  NO     88     85     85     84     84     84     85
29    A   NR  PL     63     62     60     60     58     56     56
30    A   NR  PT     64     62     63     64     62     61     62
31    A   NR  RO     46     48     48     47     44     44     45
32    A   NR  RS     40     42     41     39     39     38     38
33    A   NR  RU     29     29     29     28     28     30     29
34    A   NR  SE     89     88     84     85     85     85     85
35    A   NR  SI     60     61     61     60     60     60     57
36    A   NR  SK     51     51     50     50     50     49     52
37    A   NR  TR     42     41     40     41     39     40     38
38    A   NR  UK     81     81     82     80     77     77     78
39    A   NR  US     76     74     75     71     69     67     67

In [5]:
cleandf = df.drop(columns=['freq'])

cleandf

   unit geo  2015   2016   2017   2018   2019   2020   2021
0    NR  AL     36     39     38     36     35     36     35
1    NR  AT     76     75     75     76     77     76     74
2    NR  BE     77     77     75     75     75     76     73
3    NR  BG     41     41     43     42     43     44     42
4    NR  CH     86     86     85     85     85     85     84
5    NR  CY     61     55     57     59     58     57     53
6    NR  CZ     56     55     57     59     56     54     54
7    NR  DE     81     81     81     80     80     80     80
8    NR  DK     91     90     88     88     87     88     88
9    NR  EE     70     70     71     73     74     75     74
10   NR  EL     46     44     48     45     48     50     49
11   NR  ES     58     58     57     58     62     62     61
12   NR  FI     90     89     85     85     86     85     88
13   NR  FR     70     69     70     72     69     69     71
14   NR  HR     51     49     49     48     47     47     47
15   NR  HU     51     48     45     46     44     44     43
16   NR  IE     75     73     74     73     74     72     74
17   NR  IS     79     78     77     76     78     75     74
18   NR  IT     44     47     50     52     53     53     56
19   NR  JP     75     72     73     73     73     74     73
20   NR  KR     54     53     54     57     59     61     62
21   NR  LT     59     59     59     59     60     60     61
22   NR  LU     85     81     82     81     80     80     81
23   NR  LV     56     57     58     58     56     57     59
24   NR  ME     44     45     46     45     45     45     46
25   NR  MK     42     37     35     37     35     35     39
26   NR  MT     60     55     56     54     54     53     54
27   NR  NL     84     83     82     82     82     82     82
28   NR  NO     88     85     85     84     84     84     85
29   NR  PL     63     62     60     60     58     56     56
30   NR  PT     64     62     63     64     62     61     62
31   NR  RO     46     48     48     47     44     44     45
32   NR  RS     40     42     41     39     39     38     38
33   NR  RU     29     29     29     28     28     30     29
34   NR  SE     89     88     84     85     85     85     85
35   NR  SI     60     61     61     60     60     60     57
36   NR  SK     51     51     50     50     50     49     52
37   NR  TR     42     41     40     41     39     40     38
38   NR  UK     81     81     82     80     77     77     78
39   NR  US     76     74     75     71     69     67     67

In [6]:
cleandf.to_csv(r'C:\Users\Francesca\Desktop\cleandf2.tsv')